name: Run code checks

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with: { node-version: 21 }
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run checks
        run: yarn lint